#!/usr/bin/env python3
"""
Main file
"""
from auth import Auth

email = 'bob@bob.com'
password = 'MyPwdOfBob'
auth = Auth()

auth.register_user(email, password)
sid = auth.create_session(email)
print(sid)
# print(auth.create_session("unknown@email.com"))
u = auth.get_user_from_session_id(sid)
print(auth.get_user_from_session_id(sid))
auth.destroy_session(u.id)
print(auth.get_user_from_session_id(sid))
